# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	#
	# Set this box to whatever virtualization model you are using
	#
	config.vm.box = "ubuntu/precise64"
	#config.vm.box = "parallels/ubuntu-12.04"

	config.vm.provider "virtualbox" do |v|
		v.memory = 512
		v.cpus = 1
	end

	config.vm.provider "parallels" do |v|
		v.memory = 512
		v.cpus = 1
	end

	config.vm.hostname = "cache"
	config.vm.network :forwarded_port, guest: 11211, host: 11211
	config.vm.provision :shell, path: "bootstrap.sh"
end
